# Generated by Django 5.0.7 on 2024-07-22 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_event_customuser_spam_subcribe_customuser_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_recommendation_sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
