# Generated by Django 5.0.7 on 2024-07-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_customuser_last_recommendation_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='spam_subcribe',
            new_name='spam_subscribe',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_over',
            field=models.TextField(blank=True),
        ),
    ]
